/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    content: {
      Attachments: () => import('#controllers/admin/content/attachments_controller'),
      PostAttributes: () => import('#controllers/admin/content/post_attributes_controller'),
      Posts: () => import('#controllers/admin/content/posts_controller'),
    },
    learn: {
      Answers: () => import('#controllers/admin/learn/answers_controller'),
      Courses: () => import('#controllers/admin/learn/courses_controller'),
      Enrollments: () => import('#controllers/admin/learn/enrollments_controller'),
      LessonExamQuestions: () => import('#controllers/admin/learn/lesson_exam_questions_controller'),
      Lessons: () => import('#controllers/admin/learn/lessons_controller'),
      Questions: () => import('#controllers/admin/learn/questions_controller'),
      Quizzes: () => import('#controllers/admin/learn/quizzes_controller'),
      SiteUsers: () => import('#controllers/admin/learn/site_users_controller'),
    },
    social: {
      Comments: () => import('#controllers/admin/social/comments_controller'),
      Replies: () => import('#controllers/admin/social/replies_controller'),
      Topics: () => import('#controllers/admin/social/topics_controller'),
    },
    store: {
      Coupons: () => import('#controllers/admin/store/coupons_controller'),
      Orders: () => import('#controllers/admin/store/orders_controller'),
      Payments: () => import('#controllers/admin/store/payments_controller'),
      ProductAttributes: () => import('#controllers/admin/store/product_attributes_controller'),
      Products: () => import('#controllers/admin/store/products_controller'),
      ShippingRules: () => import('#controllers/admin/store/shipping_rules_controller'),
    },
  },
  Auth: () => import('#controllers/auth_controller'),
  content: {
    Attachments: () => import('#controllers/content/attachments_controller'),
    Posts: () => import('#controllers/content/posts_controller'),
  },
  learn: {
    Answers: () => import('#controllers/learn/answers_controller'),
    Courses: () => import('#controllers/learn/courses_controller'),
    Enrollments: () => import('#controllers/learn/enrollments_controller'),
    Lessons: () => import('#controllers/learn/lessons_controller'),
    Questions: () => import('#controllers/learn/questions_controller'),
    Quizzes: () => import('#controllers/learn/quizzes_controller'),
  },
  Sites: () => import('#controllers/sites_controller'),
  social: {
    Comments: () => import('#controllers/social/comments_controller'),
    Replies: () => import('#controllers/social/replies_controller'),
    Topics: () => import('#controllers/social/topics_controller'),
  },
  store: {
    Addresses: () => import('#controllers/store/addresses_controller'),
    Orders: () => import('#controllers/store/orders_controller'),
    Payments: () => import('#controllers/store/payments_controller'),
    Products: () => import('#controllers/store/products_controller'),
  },
}
