/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    content: {
      Attachments: () => import('#controllers/admin/content/attachments_controller'),
      PostAttributes: () => import('#controllers/admin/content/post_attributes_controller'),
      Posts: () => import('#controllers/admin/content/posts_controller'),
    },
    social: {
      Comments: () => import('#controllers/admin/social/comments_controller'),
      Replies: () => import('#controllers/admin/social/replies_controller'),
      Topics: () => import('#controllers/admin/social/topics_controller'),
    },
  },
  Auth: () => import('#controllers/auth_controller'),
  content: {
    Attachments: () => import('#controllers/content/attachments_controller'),
    Posts: () => import('#controllers/content/posts_controller'),
  },
  Sites: () => import('#controllers/sites_controller'),
  social: {
    Comments: () => import('#controllers/social/comments_controller'),
    Replies: () => import('#controllers/social/replies_controller'),
    Topics: () => import('#controllers/social/topics_controller'),
  },
}
