/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'auth.register': {
    methods: ["POST"],
    pattern: '/auth/register',
    tokens: [{"old":"/auth/register","type":0,"val":"auth","end":""},{"old":"/auth/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['auth.register']['types'],
  },
  'auth.send_verification_email': {
    methods: ["POST"],
    pattern: '/auth/send-verification-email',
    tokens: [{"old":"/auth/send-verification-email","type":0,"val":"auth","end":""},{"old":"/auth/send-verification-email","type":0,"val":"send-verification-email","end":""}],
    types: placeholder as Registry['auth.send_verification_email']['types'],
  },
  'auth.validate': {
    methods: ["GET","HEAD"],
    pattern: '/auth/verify-email/:enrollmentId',
    tokens: [{"old":"/auth/verify-email/:enrollmentId","type":0,"val":"auth","end":""},{"old":"/auth/verify-email/:enrollmentId","type":0,"val":"verify-email","end":""},{"old":"/auth/verify-email/:enrollmentId","type":1,"val":"enrollmentId","end":""}],
    types: placeholder as Registry['auth.validate']['types'],
  },
  'auth.login': {
    methods: ["POST"],
    pattern: '/auth/login',
    tokens: [{"old":"/auth/login","type":0,"val":"auth","end":""},{"old":"/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.login']['types'],
  },
  'auth.get_google_url': {
    methods: ["GET","HEAD"],
    pattern: '/auth/google/url',
    tokens: [{"old":"/auth/google/url","type":0,"val":"auth","end":""},{"old":"/auth/google/url","type":0,"val":"google","end":""},{"old":"/auth/google/url","type":0,"val":"url","end":""}],
    types: placeholder as Registry['auth.get_google_url']['types'],
  },
  'auth.handle_callback': {
    methods: ["GET","HEAD"],
    pattern: '/auth/google/handle',
    tokens: [{"old":"/auth/google/handle","type":0,"val":"auth","end":""},{"old":"/auth/google/handle","type":0,"val":"google","end":""},{"old":"/auth/google/handle","type":0,"val":"handle","end":""}],
    types: placeholder as Registry['auth.handle_callback']['types'],
  },
  'auth.logout': {
    methods: ["POST"],
    pattern: '/auth/logout',
    tokens: [{"old":"/auth/logout","type":0,"val":"auth","end":""},{"old":"/auth/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['auth.logout']['types'],
  },
  'auth.me': {
    methods: ["GET","HEAD"],
    pattern: '/auth/me',
    tokens: [{"old":"/auth/me","type":0,"val":"auth","end":""},{"old":"/auth/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['auth.me']['types'],
  },
  'sites.index': {
    methods: ["GET","HEAD"],
    pattern: '/sites',
    tokens: [{"old":"/sites","type":0,"val":"sites","end":""}],
    types: placeholder as Registry['sites.index']['types'],
  },
  'sites.show': {
    methods: ["GET","HEAD"],
    pattern: '/sites/:id',
    tokens: [{"old":"/sites/:id","type":0,"val":"sites","end":""},{"old":"/sites/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['sites.show']['types'],
  },
  'content.posts.index': {
    methods: ["GET","HEAD"],
    pattern: '/content/posts',
    tokens: [{"old":"/content/posts","type":0,"val":"content","end":""},{"old":"/content/posts","type":0,"val":"posts","end":""}],
    types: placeholder as Registry['content.posts.index']['types'],
  },
  'content.posts.show': {
    methods: ["GET","HEAD"],
    pattern: '/content/posts/:id',
    tokens: [{"old":"/content/posts/:id","type":0,"val":"content","end":""},{"old":"/content/posts/:id","type":0,"val":"posts","end":""},{"old":"/content/posts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['content.posts.show']['types'],
  },
  'content.attachments.index': {
    methods: ["GET","HEAD"],
    pattern: '/content/attachments',
    tokens: [{"old":"/content/attachments","type":0,"val":"content","end":""},{"old":"/content/attachments","type":0,"val":"attachments","end":""}],
    types: placeholder as Registry['content.attachments.index']['types'],
  },
  'content.attachments.store': {
    methods: ["POST"],
    pattern: '/content/attachments',
    tokens: [{"old":"/content/attachments","type":0,"val":"content","end":""},{"old":"/content/attachments","type":0,"val":"attachments","end":""}],
    types: placeholder as Registry['content.attachments.store']['types'],
  },
  'content.attachments.destroy': {
    methods: ["DELETE"],
    pattern: '/content/attachments/:id',
    tokens: [{"old":"/content/attachments/:id","type":0,"val":"content","end":""},{"old":"/content/attachments/:id","type":0,"val":"attachments","end":""},{"old":"/content/attachments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['content.attachments.destroy']['types'],
  },
  'social.comments.index': {
    methods: ["GET","HEAD"],
    pattern: '/social/comments',
    tokens: [{"old":"/social/comments","type":0,"val":"social","end":""},{"old":"/social/comments","type":0,"val":"comments","end":""}],
    types: placeholder as Registry['social.comments.index']['types'],
  },
  'social.comments.show': {
    methods: ["GET","HEAD"],
    pattern: '/social/comments/:id',
    tokens: [{"old":"/social/comments/:id","type":0,"val":"social","end":""},{"old":"/social/comments/:id","type":0,"val":"comments","end":""},{"old":"/social/comments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['social.comments.show']['types'],
  },
  'social.comments.store': {
    methods: ["POST"],
    pattern: '/social/comments',
    tokens: [{"old":"/social/comments","type":0,"val":"social","end":""},{"old":"/social/comments","type":0,"val":"comments","end":""}],
    types: placeholder as Registry['social.comments.store']['types'],
  },
  'social.comments.update': {
    methods: ["PUT","PATCH"],
    pattern: '/social/comments/:id',
    tokens: [{"old":"/social/comments/:id","type":0,"val":"social","end":""},{"old":"/social/comments/:id","type":0,"val":"comments","end":""},{"old":"/social/comments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['social.comments.update']['types'],
  },
  'social.topics.index': {
    methods: ["GET","HEAD"],
    pattern: '/social/topics',
    tokens: [{"old":"/social/topics","type":0,"val":"social","end":""},{"old":"/social/topics","type":0,"val":"topics","end":""}],
    types: placeholder as Registry['social.topics.index']['types'],
  },
  'social.topics.show': {
    methods: ["GET","HEAD"],
    pattern: '/social/topics/:id',
    tokens: [{"old":"/social/topics/:id","type":0,"val":"social","end":""},{"old":"/social/topics/:id","type":0,"val":"topics","end":""},{"old":"/social/topics/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['social.topics.show']['types'],
  },
  'social.topics.store': {
    methods: ["POST"],
    pattern: '/social/topics',
    tokens: [{"old":"/social/topics","type":0,"val":"social","end":""},{"old":"/social/topics","type":0,"val":"topics","end":""}],
    types: placeholder as Registry['social.topics.store']['types'],
  },
  'social.replies.store': {
    methods: ["POST"],
    pattern: '/social/topics/:topic_id/replies',
    tokens: [{"old":"/social/topics/:topic_id/replies","type":0,"val":"social","end":""},{"old":"/social/topics/:topic_id/replies","type":0,"val":"topics","end":""},{"old":"/social/topics/:topic_id/replies","type":1,"val":"topic_id","end":""},{"old":"/social/topics/:topic_id/replies","type":0,"val":"replies","end":""}],
    types: placeholder as Registry['social.replies.store']['types'],
  },
  'store.products.index': {
    methods: ["GET","HEAD"],
    pattern: '/store/products',
    tokens: [{"old":"/store/products","type":0,"val":"store","end":""},{"old":"/store/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['store.products.index']['types'],
  },
  'store.products.show': {
    methods: ["GET","HEAD"],
    pattern: '/store/products/:id',
    tokens: [{"old":"/store/products/:id","type":0,"val":"store","end":""},{"old":"/store/products/:id","type":0,"val":"products","end":""},{"old":"/store/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['store.products.show']['types'],
  },
  'store.addresses.index': {
    methods: ["GET","HEAD"],
    pattern: '/store/addresses',
    tokens: [{"old":"/store/addresses","type":0,"val":"store","end":""},{"old":"/store/addresses","type":0,"val":"addresses","end":""}],
    types: placeholder as Registry['store.addresses.index']['types'],
  },
  'store.addresses.store': {
    methods: ["POST"],
    pattern: '/store/addresses',
    tokens: [{"old":"/store/addresses","type":0,"val":"store","end":""},{"old":"/store/addresses","type":0,"val":"addresses","end":""}],
    types: placeholder as Registry['store.addresses.store']['types'],
  },
  'store.addresses.show': {
    methods: ["GET","HEAD"],
    pattern: '/store/addresses/:id',
    tokens: [{"old":"/store/addresses/:id","type":0,"val":"store","end":""},{"old":"/store/addresses/:id","type":0,"val":"addresses","end":""},{"old":"/store/addresses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['store.addresses.show']['types'],
  },
  'store.addresses.update': {
    methods: ["PUT","PATCH"],
    pattern: '/store/addresses/:id',
    tokens: [{"old":"/store/addresses/:id","type":0,"val":"store","end":""},{"old":"/store/addresses/:id","type":0,"val":"addresses","end":""},{"old":"/store/addresses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['store.addresses.update']['types'],
  },
  'store.addresses.destroy': {
    methods: ["DELETE"],
    pattern: '/store/addresses/:id',
    tokens: [{"old":"/store/addresses/:id","type":0,"val":"store","end":""},{"old":"/store/addresses/:id","type":0,"val":"addresses","end":""},{"old":"/store/addresses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['store.addresses.destroy']['types'],
  },
  'store.orders.index': {
    methods: ["GET","HEAD"],
    pattern: '/store/orders',
    tokens: [{"old":"/store/orders","type":0,"val":"store","end":""},{"old":"/store/orders","type":0,"val":"orders","end":""}],
    types: placeholder as Registry['store.orders.index']['types'],
  },
  'store.orders.store': {
    methods: ["POST"],
    pattern: '/store/orders',
    tokens: [{"old":"/store/orders","type":0,"val":"store","end":""},{"old":"/store/orders","type":0,"val":"orders","end":""}],
    types: placeholder as Registry['store.orders.store']['types'],
  },
  'store.orders.show': {
    methods: ["GET","HEAD"],
    pattern: '/store/orders/:id',
    tokens: [{"old":"/store/orders/:id","type":0,"val":"store","end":""},{"old":"/store/orders/:id","type":0,"val":"orders","end":""},{"old":"/store/orders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['store.orders.show']['types'],
  },
  'store.payments.index': {
    methods: ["GET","HEAD"],
    pattern: '/store/payments',
    tokens: [{"old":"/store/payments","type":0,"val":"store","end":""},{"old":"/store/payments","type":0,"val":"payments","end":""}],
    types: placeholder as Registry['store.payments.index']['types'],
  },
  'store.payments.store': {
    methods: ["POST"],
    pattern: '/store/payments',
    tokens: [{"old":"/store/payments","type":0,"val":"store","end":""},{"old":"/store/payments","type":0,"val":"payments","end":""}],
    types: placeholder as Registry['store.payments.store']['types'],
  },
  'store.payments.show': {
    methods: ["GET","HEAD"],
    pattern: '/store/payments/:id',
    tokens: [{"old":"/store/payments/:id","type":0,"val":"store","end":""},{"old":"/store/payments/:id","type":0,"val":"payments","end":""},{"old":"/store/payments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['store.payments.show']['types'],
  },
  'learn.courses.index': {
    methods: ["GET","HEAD"],
    pattern: '/learn/courses',
    tokens: [{"old":"/learn/courses","type":0,"val":"learn","end":""},{"old":"/learn/courses","type":0,"val":"courses","end":""}],
    types: placeholder as Registry['learn.courses.index']['types'],
  },
  'learn.courses.show': {
    methods: ["GET","HEAD"],
    pattern: '/learn/courses/:id',
    tokens: [{"old":"/learn/courses/:id","type":0,"val":"learn","end":""},{"old":"/learn/courses/:id","type":0,"val":"courses","end":""},{"old":"/learn/courses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['learn.courses.show']['types'],
  },
  'learn.courses.lessons.index': {
    methods: ["GET","HEAD"],
    pattern: '/learn/courses/:course_id/lessons',
    tokens: [{"old":"/learn/courses/:course_id/lessons","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/lessons","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/lessons","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/lessons","type":0,"val":"lessons","end":""}],
    types: placeholder as Registry['learn.courses.lessons.index']['types'],
  },
  'learn.courses.lessons.show': {
    methods: ["GET","HEAD"],
    pattern: '/learn/courses/:course_id/lessons/:id',
    tokens: [{"old":"/learn/courses/:course_id/lessons/:id","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/lessons/:id","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/lessons/:id","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/lessons/:id","type":0,"val":"lessons","end":""},{"old":"/learn/courses/:course_id/lessons/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['learn.courses.lessons.show']['types'],
  },
  'learn.courses.lessons.store': {
    methods: ["POST"],
    pattern: '/learn/courses/:course_id/lessons',
    tokens: [{"old":"/learn/courses/:course_id/lessons","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/lessons","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/lessons","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/lessons","type":0,"val":"lessons","end":""}],
    types: placeholder as Registry['learn.courses.lessons.store']['types'],
  },
  'learn.courses.lessons.update': {
    methods: ["PUT","PATCH"],
    pattern: '/learn/courses/:course_id/lessons/:id',
    tokens: [{"old":"/learn/courses/:course_id/lessons/:id","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/lessons/:id","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/lessons/:id","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/lessons/:id","type":0,"val":"lessons","end":""},{"old":"/learn/courses/:course_id/lessons/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['learn.courses.lessons.update']['types'],
  },
  'learn.courses.lessons.destroy': {
    methods: ["DELETE"],
    pattern: '/learn/courses/:course_id/lessons/:id',
    tokens: [{"old":"/learn/courses/:course_id/lessons/:id","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/lessons/:id","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/lessons/:id","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/lessons/:id","type":0,"val":"lessons","end":""},{"old":"/learn/courses/:course_id/lessons/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['learn.courses.lessons.destroy']['types'],
  },
  'learn.courses.questions.index': {
    methods: ["GET","HEAD"],
    pattern: '/learn/courses/:course_id/questions',
    tokens: [{"old":"/learn/courses/:course_id/questions","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/questions","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/questions","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/questions","type":0,"val":"questions","end":""}],
    types: placeholder as Registry['learn.courses.questions.index']['types'],
  },
  'learn.courses.questions.show': {
    methods: ["GET","HEAD"],
    pattern: '/learn/courses/:course_id/questions/:id',
    tokens: [{"old":"/learn/courses/:course_id/questions/:id","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/questions/:id","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/questions/:id","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/questions/:id","type":0,"val":"questions","end":""},{"old":"/learn/courses/:course_id/questions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['learn.courses.questions.show']['types'],
  },
  'learn.courses.questions.update': {
    methods: ["PUT","PATCH"],
    pattern: '/learn/courses/:course_id/questions/:id',
    tokens: [{"old":"/learn/courses/:course_id/questions/:id","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/questions/:id","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/questions/:id","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/questions/:id","type":0,"val":"questions","end":""},{"old":"/learn/courses/:course_id/questions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['learn.courses.questions.update']['types'],
  },
  'learn.courses.questions.store': {
    methods: ["POST"],
    pattern: '/learn/courses/:course_id/questions',
    tokens: [{"old":"/learn/courses/:course_id/questions","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/questions","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/questions","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/questions","type":0,"val":"questions","end":""}],
    types: placeholder as Registry['learn.courses.questions.store']['types'],
  },
  'learn.courses.questions.destroy': {
    methods: ["DELETE"],
    pattern: '/learn/courses/:course_id/questions/:id',
    tokens: [{"old":"/learn/courses/:course_id/questions/:id","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/questions/:id","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/questions/:id","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/questions/:id","type":0,"val":"questions","end":""},{"old":"/learn/courses/:course_id/questions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['learn.courses.questions.destroy']['types'],
  },
  'learn.courses.enrollments.store': {
    methods: ["POST"],
    pattern: '/learn/courses/:course_id/enrollments',
    tokens: [{"old":"/learn/courses/:course_id/enrollments","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/enrollments","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/enrollments","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/enrollments","type":0,"val":"enrollments","end":""}],
    types: placeholder as Registry['learn.courses.enrollments.store']['types'],
  },
  'learn.courses.enrollments.index': {
    methods: ["GET","HEAD"],
    pattern: '/learn/courses/:course_id/enrollments',
    tokens: [{"old":"/learn/courses/:course_id/enrollments","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/enrollments","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/enrollments","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/enrollments","type":0,"val":"enrollments","end":""}],
    types: placeholder as Registry['learn.courses.enrollments.index']['types'],
  },
  'learn.courses.enrollments.show': {
    methods: ["GET","HEAD"],
    pattern: '/learn/courses/:course_id/enrollments/:id',
    tokens: [{"old":"/learn/courses/:course_id/enrollments/:id","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/enrollments/:id","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/enrollments/:id","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/enrollments/:id","type":0,"val":"enrollments","end":""},{"old":"/learn/courses/:course_id/enrollments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['learn.courses.enrollments.show']['types'],
  },
  'learn.courses.lessons.answers.store': {
    methods: ["POST"],
    pattern: '/learn/courses/:course_id/lessons/:lesson_id/answers',
    tokens: [{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers","type":0,"val":"lessons","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers","type":1,"val":"lesson_id","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers","type":0,"val":"answers","end":""}],
    types: placeholder as Registry['learn.courses.lessons.answers.store']['types'],
  },
  'learn.courses.lessons.answers.show': {
    methods: ["GET","HEAD"],
    pattern: '/learn/courses/:course_id/lessons/:lesson_id/answers/:id',
    tokens: [{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"lessons","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":1,"val":"lesson_id","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"answers","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['learn.courses.lessons.answers.show']['types'],
  },
  'learn.courses.lessons.answers.index': {
    methods: ["GET","HEAD"],
    pattern: '/learn/courses/:course_id/lessons/:lesson_id/answers',
    tokens: [{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers","type":0,"val":"lessons","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers","type":1,"val":"lesson_id","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers","type":0,"val":"answers","end":""}],
    types: placeholder as Registry['learn.courses.lessons.answers.index']['types'],
  },
  'learn.courses.lessons.answers.update': {
    methods: ["PUT","PATCH"],
    pattern: '/learn/courses/:course_id/lessons/:lesson_id/answers/:id',
    tokens: [{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"lessons","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":1,"val":"lesson_id","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"answers","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['learn.courses.lessons.answers.update']['types'],
  },
  'learn.courses.lessons.answers.destroy': {
    methods: ["DELETE"],
    pattern: '/learn/courses/:course_id/lessons/:lesson_id/answers/:id',
    tokens: [{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"lessons","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":1,"val":"lesson_id","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"answers","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['learn.courses.lessons.answers.destroy']['types'],
  },
  'learn.courses.lessons.quizzes.store': {
    methods: ["POST"],
    pattern: '/learn/courses/:course_id/lessons/:lesson_id/quizzes',
    tokens: [{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes","type":0,"val":"lessons","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes","type":1,"val":"lesson_id","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes","type":0,"val":"quizzes","end":""}],
    types: placeholder as Registry['learn.courses.lessons.quizzes.store']['types'],
  },
  'learn.courses.lessons.quizzes.show': {
    methods: ["GET","HEAD"],
    pattern: '/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id',
    tokens: [{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"lessons","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":1,"val":"lesson_id","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"quizzes","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['learn.courses.lessons.quizzes.show']['types'],
  },
  'learn.courses.lessons.quizzes.index': {
    methods: ["GET","HEAD"],
    pattern: '/learn/courses/:course_id/lessons/:lesson_id/quizzes',
    tokens: [{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes","type":0,"val":"lessons","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes","type":1,"val":"lesson_id","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes","type":0,"val":"quizzes","end":""}],
    types: placeholder as Registry['learn.courses.lessons.quizzes.index']['types'],
  },
  'learn.courses.lessons.quizzes.update': {
    methods: ["PUT","PATCH"],
    pattern: '/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id',
    tokens: [{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"lessons","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":1,"val":"lesson_id","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"quizzes","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['learn.courses.lessons.quizzes.update']['types'],
  },
  'learn.courses.lessons.quizzes.destroy': {
    methods: ["DELETE"],
    pattern: '/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id',
    tokens: [{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"learn","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"courses","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":1,"val":"course_id","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"lessons","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":1,"val":"lesson_id","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"quizzes","end":""},{"old":"/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['learn.courses.lessons.quizzes.destroy']['types'],
  },
  'admin.content.posts.import': {
    methods: ["POST"],
    pattern: '/admin/content/posts/import',
    tokens: [{"old":"/admin/content/posts/import","type":0,"val":"admin","end":""},{"old":"/admin/content/posts/import","type":0,"val":"content","end":""},{"old":"/admin/content/posts/import","type":0,"val":"posts","end":""},{"old":"/admin/content/posts/import","type":0,"val":"import","end":""}],
    types: placeholder as Registry['admin.content.posts.import']['types'],
  },
  'admin.content.posts.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/content/posts',
    tokens: [{"old":"/admin/content/posts","type":0,"val":"admin","end":""},{"old":"/admin/content/posts","type":0,"val":"content","end":""},{"old":"/admin/content/posts","type":0,"val":"posts","end":""}],
    types: placeholder as Registry['admin.content.posts.index']['types'],
  },
  'admin.content.posts.store': {
    methods: ["POST"],
    pattern: '/admin/content/posts',
    tokens: [{"old":"/admin/content/posts","type":0,"val":"admin","end":""},{"old":"/admin/content/posts","type":0,"val":"content","end":""},{"old":"/admin/content/posts","type":0,"val":"posts","end":""}],
    types: placeholder as Registry['admin.content.posts.store']['types'],
  },
  'admin.content.posts.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/content/posts/:id',
    tokens: [{"old":"/admin/content/posts/:id","type":0,"val":"admin","end":""},{"old":"/admin/content/posts/:id","type":0,"val":"content","end":""},{"old":"/admin/content/posts/:id","type":0,"val":"posts","end":""},{"old":"/admin/content/posts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.content.posts.show']['types'],
  },
  'admin.content.posts.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/content/posts/:id',
    tokens: [{"old":"/admin/content/posts/:id","type":0,"val":"admin","end":""},{"old":"/admin/content/posts/:id","type":0,"val":"content","end":""},{"old":"/admin/content/posts/:id","type":0,"val":"posts","end":""},{"old":"/admin/content/posts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.content.posts.update']['types'],
  },
  'admin.content.posts.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/content/posts/:id',
    tokens: [{"old":"/admin/content/posts/:id","type":0,"val":"admin","end":""},{"old":"/admin/content/posts/:id","type":0,"val":"content","end":""},{"old":"/admin/content/posts/:id","type":0,"val":"posts","end":""},{"old":"/admin/content/posts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.content.posts.destroy']['types'],
  },
  'admin.content.posts.attributes.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/content/posts/:post_id/attributes',
    tokens: [{"old":"/admin/content/posts/:post_id/attributes","type":0,"val":"admin","end":""},{"old":"/admin/content/posts/:post_id/attributes","type":0,"val":"content","end":""},{"old":"/admin/content/posts/:post_id/attributes","type":0,"val":"posts","end":""},{"old":"/admin/content/posts/:post_id/attributes","type":1,"val":"post_id","end":""},{"old":"/admin/content/posts/:post_id/attributes","type":0,"val":"attributes","end":""}],
    types: placeholder as Registry['admin.content.posts.attributes.index']['types'],
  },
  'admin.content.posts.attributes.store': {
    methods: ["POST"],
    pattern: '/admin/content/posts/:post_id/attributes',
    tokens: [{"old":"/admin/content/posts/:post_id/attributes","type":0,"val":"admin","end":""},{"old":"/admin/content/posts/:post_id/attributes","type":0,"val":"content","end":""},{"old":"/admin/content/posts/:post_id/attributes","type":0,"val":"posts","end":""},{"old":"/admin/content/posts/:post_id/attributes","type":1,"val":"post_id","end":""},{"old":"/admin/content/posts/:post_id/attributes","type":0,"val":"attributes","end":""}],
    types: placeholder as Registry['admin.content.posts.attributes.store']['types'],
  },
  'admin.content.posts.attributes.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/content/posts/:post_id/attributes/:id',
    tokens: [{"old":"/admin/content/posts/:post_id/attributes/:id","type":0,"val":"admin","end":""},{"old":"/admin/content/posts/:post_id/attributes/:id","type":0,"val":"content","end":""},{"old":"/admin/content/posts/:post_id/attributes/:id","type":0,"val":"posts","end":""},{"old":"/admin/content/posts/:post_id/attributes/:id","type":1,"val":"post_id","end":""},{"old":"/admin/content/posts/:post_id/attributes/:id","type":0,"val":"attributes","end":""},{"old":"/admin/content/posts/:post_id/attributes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.content.posts.attributes.destroy']['types'],
  },
  'admin.content.attachments.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/content/attachments',
    tokens: [{"old":"/admin/content/attachments","type":0,"val":"admin","end":""},{"old":"/admin/content/attachments","type":0,"val":"content","end":""},{"old":"/admin/content/attachments","type":0,"val":"attachments","end":""}],
    types: placeholder as Registry['admin.content.attachments.index']['types'],
  },
  'admin.content.attachments.store': {
    methods: ["POST"],
    pattern: '/admin/content/attachments',
    tokens: [{"old":"/admin/content/attachments","type":0,"val":"admin","end":""},{"old":"/admin/content/attachments","type":0,"val":"content","end":""},{"old":"/admin/content/attachments","type":0,"val":"attachments","end":""}],
    types: placeholder as Registry['admin.content.attachments.store']['types'],
  },
  'admin.content.attachments.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/content/attachments/:id',
    tokens: [{"old":"/admin/content/attachments/:id","type":0,"val":"admin","end":""},{"old":"/admin/content/attachments/:id","type":0,"val":"content","end":""},{"old":"/admin/content/attachments/:id","type":0,"val":"attachments","end":""},{"old":"/admin/content/attachments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.content.attachments.destroy']['types'],
  },
  'admin.content.attachments.import': {
    methods: ["GET","HEAD"],
    pattern: '/admin/content/attachments/import',
    tokens: [{"old":"/admin/content/attachments/import","type":0,"val":"admin","end":""},{"old":"/admin/content/attachments/import","type":0,"val":"content","end":""},{"old":"/admin/content/attachments/import","type":0,"val":"attachments","end":""},{"old":"/admin/content/attachments/import","type":0,"val":"import","end":""}],
    types: placeholder as Registry['admin.content.attachments.import']['types'],
  },
  'admin.social.comments.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/social/comments',
    tokens: [{"old":"/admin/social/comments","type":0,"val":"admin","end":""},{"old":"/admin/social/comments","type":0,"val":"social","end":""},{"old":"/admin/social/comments","type":0,"val":"comments","end":""}],
    types: placeholder as Registry['admin.social.comments.index']['types'],
  },
  'admin.social.comments.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/social/comments/:id',
    tokens: [{"old":"/admin/social/comments/:id","type":0,"val":"admin","end":""},{"old":"/admin/social/comments/:id","type":0,"val":"social","end":""},{"old":"/admin/social/comments/:id","type":0,"val":"comments","end":""},{"old":"/admin/social/comments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.social.comments.show']['types'],
  },
  'admin.social.comments.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/social/comments/:id',
    tokens: [{"old":"/admin/social/comments/:id","type":0,"val":"admin","end":""},{"old":"/admin/social/comments/:id","type":0,"val":"social","end":""},{"old":"/admin/social/comments/:id","type":0,"val":"comments","end":""},{"old":"/admin/social/comments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.social.comments.update']['types'],
  },
  'admin.social.comments.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/social/comments/:id',
    tokens: [{"old":"/admin/social/comments/:id","type":0,"val":"admin","end":""},{"old":"/admin/social/comments/:id","type":0,"val":"social","end":""},{"old":"/admin/social/comments/:id","type":0,"val":"comments","end":""},{"old":"/admin/social/comments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.social.comments.destroy']['types'],
  },
  'admin.social.topics.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/social/topics',
    tokens: [{"old":"/admin/social/topics","type":0,"val":"admin","end":""},{"old":"/admin/social/topics","type":0,"val":"social","end":""},{"old":"/admin/social/topics","type":0,"val":"topics","end":""}],
    types: placeholder as Registry['admin.social.topics.index']['types'],
  },
  'admin.social.topics.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/social/topics/:id',
    tokens: [{"old":"/admin/social/topics/:id","type":0,"val":"admin","end":""},{"old":"/admin/social/topics/:id","type":0,"val":"social","end":""},{"old":"/admin/social/topics/:id","type":0,"val":"topics","end":""},{"old":"/admin/social/topics/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.social.topics.show']['types'],
  },
  'admin.social.topics.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/social/topics/:id',
    tokens: [{"old":"/admin/social/topics/:id","type":0,"val":"admin","end":""},{"old":"/admin/social/topics/:id","type":0,"val":"social","end":""},{"old":"/admin/social/topics/:id","type":0,"val":"topics","end":""},{"old":"/admin/social/topics/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.social.topics.update']['types'],
  },
  'admin.social.topics.replies.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/social/topics/:topic_id/replies',
    tokens: [{"old":"/admin/social/topics/:topic_id/replies","type":0,"val":"admin","end":""},{"old":"/admin/social/topics/:topic_id/replies","type":0,"val":"social","end":""},{"old":"/admin/social/topics/:topic_id/replies","type":0,"val":"topics","end":""},{"old":"/admin/social/topics/:topic_id/replies","type":1,"val":"topic_id","end":""},{"old":"/admin/social/topics/:topic_id/replies","type":0,"val":"replies","end":""}],
    types: placeholder as Registry['admin.social.topics.replies.index']['types'],
  },
  'admin.store.products.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/store/products',
    tokens: [{"old":"/admin/store/products","type":0,"val":"admin","end":""},{"old":"/admin/store/products","type":0,"val":"store","end":""},{"old":"/admin/store/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['admin.store.products.index']['types'],
  },
  'admin.store.products.store': {
    methods: ["POST"],
    pattern: '/admin/store/products',
    tokens: [{"old":"/admin/store/products","type":0,"val":"admin","end":""},{"old":"/admin/store/products","type":0,"val":"store","end":""},{"old":"/admin/store/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['admin.store.products.store']['types'],
  },
  'admin.store.products.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/store/products/:id',
    tokens: [{"old":"/admin/store/products/:id","type":0,"val":"admin","end":""},{"old":"/admin/store/products/:id","type":0,"val":"store","end":""},{"old":"/admin/store/products/:id","type":0,"val":"products","end":""},{"old":"/admin/store/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.store.products.show']['types'],
  },
  'admin.store.products.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/store/products/:id',
    tokens: [{"old":"/admin/store/products/:id","type":0,"val":"admin","end":""},{"old":"/admin/store/products/:id","type":0,"val":"store","end":""},{"old":"/admin/store/products/:id","type":0,"val":"products","end":""},{"old":"/admin/store/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.store.products.update']['types'],
  },
  'admin.store.products.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/store/products/:id',
    tokens: [{"old":"/admin/store/products/:id","type":0,"val":"admin","end":""},{"old":"/admin/store/products/:id","type":0,"val":"store","end":""},{"old":"/admin/store/products/:id","type":0,"val":"products","end":""},{"old":"/admin/store/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.store.products.destroy']['types'],
  },
  'admin.store.products.attributes.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/store/products/:product_id/attributes',
    tokens: [{"old":"/admin/store/products/:product_id/attributes","type":0,"val":"admin","end":""},{"old":"/admin/store/products/:product_id/attributes","type":0,"val":"store","end":""},{"old":"/admin/store/products/:product_id/attributes","type":0,"val":"products","end":""},{"old":"/admin/store/products/:product_id/attributes","type":1,"val":"product_id","end":""},{"old":"/admin/store/products/:product_id/attributes","type":0,"val":"attributes","end":""}],
    types: placeholder as Registry['admin.store.products.attributes.index']['types'],
  },
  'admin.store.products.attributes.store': {
    methods: ["POST"],
    pattern: '/admin/store/products/:product_id/attributes',
    tokens: [{"old":"/admin/store/products/:product_id/attributes","type":0,"val":"admin","end":""},{"old":"/admin/store/products/:product_id/attributes","type":0,"val":"store","end":""},{"old":"/admin/store/products/:product_id/attributes","type":0,"val":"products","end":""},{"old":"/admin/store/products/:product_id/attributes","type":1,"val":"product_id","end":""},{"old":"/admin/store/products/:product_id/attributes","type":0,"val":"attributes","end":""}],
    types: placeholder as Registry['admin.store.products.attributes.store']['types'],
  },
  'admin.store.products.attributes.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/store/products/:product_id/attributes/:id',
    tokens: [{"old":"/admin/store/products/:product_id/attributes/:id","type":0,"val":"admin","end":""},{"old":"/admin/store/products/:product_id/attributes/:id","type":0,"val":"store","end":""},{"old":"/admin/store/products/:product_id/attributes/:id","type":0,"val":"products","end":""},{"old":"/admin/store/products/:product_id/attributes/:id","type":1,"val":"product_id","end":""},{"old":"/admin/store/products/:product_id/attributes/:id","type":0,"val":"attributes","end":""},{"old":"/admin/store/products/:product_id/attributes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.store.products.attributes.destroy']['types'],
  },
  'admin.store.orders.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/store/orders',
    tokens: [{"old":"/admin/store/orders","type":0,"val":"admin","end":""},{"old":"/admin/store/orders","type":0,"val":"store","end":""},{"old":"/admin/store/orders","type":0,"val":"orders","end":""}],
    types: placeholder as Registry['admin.store.orders.index']['types'],
  },
  'admin.store.orders.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/store/orders/:id',
    tokens: [{"old":"/admin/store/orders/:id","type":0,"val":"admin","end":""},{"old":"/admin/store/orders/:id","type":0,"val":"store","end":""},{"old":"/admin/store/orders/:id","type":0,"val":"orders","end":""},{"old":"/admin/store/orders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.store.orders.show']['types'],
  },
  'admin.store.orders.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/store/orders/:id',
    tokens: [{"old":"/admin/store/orders/:id","type":0,"val":"admin","end":""},{"old":"/admin/store/orders/:id","type":0,"val":"store","end":""},{"old":"/admin/store/orders/:id","type":0,"val":"orders","end":""},{"old":"/admin/store/orders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.store.orders.update']['types'],
  },
  'admin.store.payments.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/store/payments',
    tokens: [{"old":"/admin/store/payments","type":0,"val":"admin","end":""},{"old":"/admin/store/payments","type":0,"val":"store","end":""},{"old":"/admin/store/payments","type":0,"val":"payments","end":""}],
    types: placeholder as Registry['admin.store.payments.index']['types'],
  },
  'admin.store.payments.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/store/payments/:id',
    tokens: [{"old":"/admin/store/payments/:id","type":0,"val":"admin","end":""},{"old":"/admin/store/payments/:id","type":0,"val":"store","end":""},{"old":"/admin/store/payments/:id","type":0,"val":"payments","end":""},{"old":"/admin/store/payments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.store.payments.show']['types'],
  },
  'admin.store.payments.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/store/payments/:id',
    tokens: [{"old":"/admin/store/payments/:id","type":0,"val":"admin","end":""},{"old":"/admin/store/payments/:id","type":0,"val":"store","end":""},{"old":"/admin/store/payments/:id","type":0,"val":"payments","end":""},{"old":"/admin/store/payments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.store.payments.update']['types'],
  },
  'admin.store.coupons.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/store/coupons',
    tokens: [{"old":"/admin/store/coupons","type":0,"val":"admin","end":""},{"old":"/admin/store/coupons","type":0,"val":"store","end":""},{"old":"/admin/store/coupons","type":0,"val":"coupons","end":""}],
    types: placeholder as Registry['admin.store.coupons.index']['types'],
  },
  'admin.store.coupons.store': {
    methods: ["POST"],
    pattern: '/admin/store/coupons',
    tokens: [{"old":"/admin/store/coupons","type":0,"val":"admin","end":""},{"old":"/admin/store/coupons","type":0,"val":"store","end":""},{"old":"/admin/store/coupons","type":0,"val":"coupons","end":""}],
    types: placeholder as Registry['admin.store.coupons.store']['types'],
  },
  'admin.store.coupons.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/store/coupons/:id',
    tokens: [{"old":"/admin/store/coupons/:id","type":0,"val":"admin","end":""},{"old":"/admin/store/coupons/:id","type":0,"val":"store","end":""},{"old":"/admin/store/coupons/:id","type":0,"val":"coupons","end":""},{"old":"/admin/store/coupons/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.store.coupons.show']['types'],
  },
  'admin.store.coupons.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/store/coupons/:id',
    tokens: [{"old":"/admin/store/coupons/:id","type":0,"val":"admin","end":""},{"old":"/admin/store/coupons/:id","type":0,"val":"store","end":""},{"old":"/admin/store/coupons/:id","type":0,"val":"coupons","end":""},{"old":"/admin/store/coupons/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.store.coupons.update']['types'],
  },
  'admin.store.coupons.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/store/coupons/:id',
    tokens: [{"old":"/admin/store/coupons/:id","type":0,"val":"admin","end":""},{"old":"/admin/store/coupons/:id","type":0,"val":"store","end":""},{"old":"/admin/store/coupons/:id","type":0,"val":"coupons","end":""},{"old":"/admin/store/coupons/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.store.coupons.destroy']['types'],
  },
  'admin.store.shipping_rules.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/store/shipping-rules',
    tokens: [{"old":"/admin/store/shipping-rules","type":0,"val":"admin","end":""},{"old":"/admin/store/shipping-rules","type":0,"val":"store","end":""},{"old":"/admin/store/shipping-rules","type":0,"val":"shipping-rules","end":""}],
    types: placeholder as Registry['admin.store.shipping_rules.index']['types'],
  },
  'admin.store.shipping_rules.store': {
    methods: ["POST"],
    pattern: '/admin/store/shipping-rules',
    tokens: [{"old":"/admin/store/shipping-rules","type":0,"val":"admin","end":""},{"old":"/admin/store/shipping-rules","type":0,"val":"store","end":""},{"old":"/admin/store/shipping-rules","type":0,"val":"shipping-rules","end":""}],
    types: placeholder as Registry['admin.store.shipping_rules.store']['types'],
  },
  'admin.store.shipping_rules.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/store/shipping-rules/:id',
    tokens: [{"old":"/admin/store/shipping-rules/:id","type":0,"val":"admin","end":""},{"old":"/admin/store/shipping-rules/:id","type":0,"val":"store","end":""},{"old":"/admin/store/shipping-rules/:id","type":0,"val":"shipping-rules","end":""},{"old":"/admin/store/shipping-rules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.store.shipping_rules.show']['types'],
  },
  'admin.store.shipping_rules.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/store/shipping-rules/:id',
    tokens: [{"old":"/admin/store/shipping-rules/:id","type":0,"val":"admin","end":""},{"old":"/admin/store/shipping-rules/:id","type":0,"val":"store","end":""},{"old":"/admin/store/shipping-rules/:id","type":0,"val":"shipping-rules","end":""},{"old":"/admin/store/shipping-rules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.store.shipping_rules.update']['types'],
  },
  'admin.store.shipping_rules.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/store/shipping-rules/:id',
    tokens: [{"old":"/admin/store/shipping-rules/:id","type":0,"val":"admin","end":""},{"old":"/admin/store/shipping-rules/:id","type":0,"val":"store","end":""},{"old":"/admin/store/shipping-rules/:id","type":0,"val":"shipping-rules","end":""},{"old":"/admin/store/shipping-rules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.store.shipping_rules.destroy']['types'],
  },
  'admin.learn.courses.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/learn/courses',
    tokens: [{"old":"/admin/learn/courses","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses","type":0,"val":"courses","end":""}],
    types: placeholder as Registry['admin.learn.courses.index']['types'],
  },
  'admin.learn.courses.store': {
    methods: ["POST"],
    pattern: '/admin/learn/courses',
    tokens: [{"old":"/admin/learn/courses","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses","type":0,"val":"courses","end":""}],
    types: placeholder as Registry['admin.learn.courses.store']['types'],
  },
  'admin.learn.courses.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/learn/courses/:id',
    tokens: [{"old":"/admin/learn/courses/:id","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:id","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:id","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.learn.courses.show']['types'],
  },
  'admin.learn.courses.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/learn/courses/:id',
    tokens: [{"old":"/admin/learn/courses/:id","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:id","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:id","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.learn.courses.update']['types'],
  },
  'admin.learn.courses.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/learn/courses/:id',
    tokens: [{"old":"/admin/learn/courses/:id","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:id","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:id","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.learn.courses.destroy']['types'],
  },
  'admin.learn.courses.lessons.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/learn/courses/:course_id/lessons',
    tokens: [{"old":"/admin/learn/courses/:course_id/lessons","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/lessons","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/lessons","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/lessons","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons","type":0,"val":"lessons","end":""}],
    types: placeholder as Registry['admin.learn.courses.lessons.index']['types'],
  },
  'admin.learn.courses.lessons.store': {
    methods: ["POST"],
    pattern: '/admin/learn/courses/:course_id/lessons',
    tokens: [{"old":"/admin/learn/courses/:course_id/lessons","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/lessons","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/lessons","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/lessons","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons","type":0,"val":"lessons","end":""}],
    types: placeholder as Registry['admin.learn.courses.lessons.store']['types'],
  },
  'admin.learn.courses.lessons.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/learn/courses/:course_id/lessons/:id',
    tokens: [{"old":"/admin/learn/courses/:course_id/lessons/:id","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:id","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:id","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:id","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:id","type":0,"val":"lessons","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.learn.courses.lessons.show']['types'],
  },
  'admin.learn.courses.lessons.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/learn/courses/:course_id/lessons/:id',
    tokens: [{"old":"/admin/learn/courses/:course_id/lessons/:id","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:id","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:id","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:id","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:id","type":0,"val":"lessons","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.learn.courses.lessons.update']['types'],
  },
  'admin.learn.courses.lessons.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/learn/courses/:course_id/lessons/:id',
    tokens: [{"old":"/admin/learn/courses/:course_id/lessons/:id","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:id","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:id","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:id","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:id","type":0,"val":"lessons","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.learn.courses.lessons.destroy']['types'],
  },
  'admin.learn.courses.questions.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/learn/courses/:course_id/questions',
    tokens: [{"old":"/admin/learn/courses/:course_id/questions","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/questions","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/questions","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/questions","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/questions","type":0,"val":"questions","end":""}],
    types: placeholder as Registry['admin.learn.courses.questions.index']['types'],
  },
  'admin.learn.courses.questions.store': {
    methods: ["POST"],
    pattern: '/admin/learn/courses/:course_id/questions',
    tokens: [{"old":"/admin/learn/courses/:course_id/questions","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/questions","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/questions","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/questions","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/questions","type":0,"val":"questions","end":""}],
    types: placeholder as Registry['admin.learn.courses.questions.store']['types'],
  },
  'admin.learn.courses.questions.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/learn/courses/:course_id/questions/:id',
    tokens: [{"old":"/admin/learn/courses/:course_id/questions/:id","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/questions/:id","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/questions/:id","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/questions/:id","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/questions/:id","type":0,"val":"questions","end":""},{"old":"/admin/learn/courses/:course_id/questions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.learn.courses.questions.show']['types'],
  },
  'admin.learn.courses.questions.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/learn/courses/:course_id/questions/:id',
    tokens: [{"old":"/admin/learn/courses/:course_id/questions/:id","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/questions/:id","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/questions/:id","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/questions/:id","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/questions/:id","type":0,"val":"questions","end":""},{"old":"/admin/learn/courses/:course_id/questions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.learn.courses.questions.update']['types'],
  },
  'admin.learn.courses.questions.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/learn/courses/:course_id/questions/:id',
    tokens: [{"old":"/admin/learn/courses/:course_id/questions/:id","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/questions/:id","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/questions/:id","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/questions/:id","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/questions/:id","type":0,"val":"questions","end":""},{"old":"/admin/learn/courses/:course_id/questions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.learn.courses.questions.destroy']['types'],
  },
  'admin.learn.courses.lessons.exam_questions.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions',
    tokens: [{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions","type":0,"val":"lessons","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions","type":1,"val":"lesson_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions","type":0,"val":"exam-questions","end":""}],
    types: placeholder as Registry['admin.learn.courses.lessons.exam_questions.index']['types'],
  },
  'admin.learn.courses.lessons.exam_questions.store': {
    methods: ["POST"],
    pattern: '/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions',
    tokens: [{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions","type":0,"val":"lessons","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions","type":1,"val":"lesson_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions","type":0,"val":"exam-questions","end":""}],
    types: placeholder as Registry['admin.learn.courses.lessons.exam_questions.store']['types'],
  },
  'admin.learn.courses.lessons.exam_questions.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions/:id',
    tokens: [{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions/:id","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions/:id","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions/:id","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions/:id","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions/:id","type":0,"val":"lessons","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions/:id","type":1,"val":"lesson_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions/:id","type":0,"val":"exam-questions","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/exam-questions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.learn.courses.lessons.exam_questions.destroy']['types'],
  },
  'admin.learn.courses.lessons.answers.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/learn/courses/:course_id/lessons/:lesson_id/answers',
    tokens: [{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers","type":0,"val":"lessons","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers","type":1,"val":"lesson_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers","type":0,"val":"answers","end":""}],
    types: placeholder as Registry['admin.learn.courses.lessons.answers.index']['types'],
  },
  'admin.learn.courses.lessons.answers.store': {
    methods: ["POST"],
    pattern: '/admin/learn/courses/:course_id/lessons/:lesson_id/answers',
    tokens: [{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers","type":0,"val":"lessons","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers","type":1,"val":"lesson_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers","type":0,"val":"answers","end":""}],
    types: placeholder as Registry['admin.learn.courses.lessons.answers.store']['types'],
  },
  'admin.learn.courses.lessons.answers.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id',
    tokens: [{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"lessons","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":1,"val":"lesson_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"answers","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.learn.courses.lessons.answers.show']['types'],
  },
  'admin.learn.courses.lessons.answers.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id',
    tokens: [{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"lessons","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":1,"val":"lesson_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"answers","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.learn.courses.lessons.answers.update']['types'],
  },
  'admin.learn.courses.lessons.answers.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id',
    tokens: [{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"lessons","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":1,"val":"lesson_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":0,"val":"answers","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/answers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.learn.courses.lessons.answers.destroy']['types'],
  },
  'admin.learn.courses.lessons.quizzes.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes',
    tokens: [{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes","type":0,"val":"lessons","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes","type":1,"val":"lesson_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes","type":0,"val":"quizzes","end":""}],
    types: placeholder as Registry['admin.learn.courses.lessons.quizzes.index']['types'],
  },
  'admin.learn.courses.lessons.quizzes.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id',
    tokens: [{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"lessons","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":1,"val":"lesson_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"quizzes","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.learn.courses.lessons.quizzes.show']['types'],
  },
  'admin.learn.courses.lessons.quizzes.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id',
    tokens: [{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"lessons","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":1,"val":"lesson_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"quizzes","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.learn.courses.lessons.quizzes.update']['types'],
  },
  'admin.learn.courses.lessons.quizzes.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id',
    tokens: [{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"admin","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"learn","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"courses","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":1,"val":"course_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"lessons","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":1,"val":"lesson_id","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":0,"val":"quizzes","end":""},{"old":"/admin/learn/courses/:course_id/lessons/:lesson_id/quizzes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.learn.courses.lessons.quizzes.destroy']['types'],
  },
  'admin.learn.enrollments.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/learn/enrollments',
    tokens: [{"old":"/admin/learn/enrollments","type":0,"val":"admin","end":""},{"old":"/admin/learn/enrollments","type":0,"val":"learn","end":""},{"old":"/admin/learn/enrollments","type":0,"val":"enrollments","end":""}],
    types: placeholder as Registry['admin.learn.enrollments.index']['types'],
  },
  'admin.learn.enrollments.store': {
    methods: ["POST"],
    pattern: '/admin/learn/enrollments',
    tokens: [{"old":"/admin/learn/enrollments","type":0,"val":"admin","end":""},{"old":"/admin/learn/enrollments","type":0,"val":"learn","end":""},{"old":"/admin/learn/enrollments","type":0,"val":"enrollments","end":""}],
    types: placeholder as Registry['admin.learn.enrollments.store']['types'],
  },
  'admin.learn.enrollments.show': {
    methods: ["GET","HEAD"],
    pattern: '/admin/learn/enrollments/:id',
    tokens: [{"old":"/admin/learn/enrollments/:id","type":0,"val":"admin","end":""},{"old":"/admin/learn/enrollments/:id","type":0,"val":"learn","end":""},{"old":"/admin/learn/enrollments/:id","type":0,"val":"enrollments","end":""},{"old":"/admin/learn/enrollments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.learn.enrollments.show']['types'],
  },
  'admin.learn.enrollments.update': {
    methods: ["PUT","PATCH"],
    pattern: '/admin/learn/enrollments/:id',
    tokens: [{"old":"/admin/learn/enrollments/:id","type":0,"val":"admin","end":""},{"old":"/admin/learn/enrollments/:id","type":0,"val":"learn","end":""},{"old":"/admin/learn/enrollments/:id","type":0,"val":"enrollments","end":""},{"old":"/admin/learn/enrollments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.learn.enrollments.update']['types'],
  },
  'admin.learn.enrollments.destroy': {
    methods: ["DELETE"],
    pattern: '/admin/learn/enrollments/:id',
    tokens: [{"old":"/admin/learn/enrollments/:id","type":0,"val":"admin","end":""},{"old":"/admin/learn/enrollments/:id","type":0,"val":"learn","end":""},{"old":"/admin/learn/enrollments/:id","type":0,"val":"enrollments","end":""},{"old":"/admin/learn/enrollments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.learn.enrollments.destroy']['types'],
  },
  'admin.learn.site_users.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/learn/site-users',
    tokens: [{"old":"/admin/learn/site-users","type":0,"val":"admin","end":""},{"old":"/admin/learn/site-users","type":0,"val":"learn","end":""},{"old":"/admin/learn/site-users","type":0,"val":"site-users","end":""}],
    types: placeholder as Registry['admin.learn.site_users.index']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
