/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ContentAttachmentSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'mime', 'name', 'path', 'siteId', 'size', 'userId'] as const
  $columns = ContentAttachmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mime: string
  @column()
  declare name: string
  @column()
  declare path: string
  @column()
  declare siteId: string
  @column()
  declare size: number
  @column()
  declare userId: string
}

export class ContentAttributeSchema extends BaseModel {
  static $columns = ['contentPostId', 'id', 'name', 'type', 'value'] as const
  $columns = ContentAttributeSchema.$columns
  @column()
  declare contentPostId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare type: string
  @column()
  declare value: string
}

export class ContentPostSchema extends BaseModel {
  static $columns = ['active', 'content', 'createdAt', 'description', 'format', 'id', 'name', 'picture', 'siteId', 'slug', 'tags', 'updatedAt', 'userId'] as const
  $columns = ContentPostSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare format: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare picture: string | null
  @column()
  declare siteId: string
  @column()
  declare slug: string
  @column()
  declare tags: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class EnrollmentSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'role', 'siteId', 'updatedAt', 'userId'] as const
  $columns = EnrollmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare role: string
  @column()
  declare siteId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class LearnCourseSchema extends BaseModel {
  static $columns = ['active', 'autoEnroll', 'createdAt', 'description', 'group', 'id', 'name', 'picture', 'siteId', 'slug', 'updatedAt', 'video'] as const
  $columns = LearnCourseSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare autoEnroll: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare group: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare picture: string | null
  @column()
  declare siteId: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare video: string | null
}

export class LearnEnrollmentSchema extends BaseModel {
  static $columns = ['courseId', 'createdAt', 'id', 'progress', 'role', 'status', 'updatedAt', 'userId'] as const
  $columns = LearnEnrollmentSchema.$columns
  @column()
  declare courseId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare progress: string
  @column()
  declare role: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class LearnLessonSchema extends BaseModel {
  static $columns = ['active', 'activity', 'content', 'courseId', 'createdAt', 'description', 'format', 'id', 'limitDate', 'name', 'order', 'slug', 'updatedAt', 'video'] as const
  $columns = LearnLessonSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare activity: string | null
  @column()
  declare content: string | null
  @column()
  declare courseId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare format: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare limitDate: DateTime | null
  @column()
  declare name: string
  @column()
  declare order: number
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare video: string | null
}

export class LearnLessonAnswerSchema extends BaseModel {
  static $columns = ['answer', 'attachment', 'createdAt', 'feedback', 'id', 'learnEnrollmentId', 'lessonId', 'result', 'updatedAt'] as const
  $columns = LearnLessonAnswerSchema.$columns
  @column()
  declare answer: string
  @column()
  declare attachment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare feedback: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare learnEnrollmentId: string
  @column()
  declare lessonId: string
  @column()
  declare result: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LearnLessonQuestionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'lessonId', 'questionId', 'updatedAt'] as const
  $columns = LearnLessonQuestionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lessonId: string
  @column()
  declare questionId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LearnLessonQuestionsQuizzSchema extends BaseModel {
  static $columns = ['answers', 'createdAt', 'id', 'learnEnrollmentId', 'lessonId', 'questions', 'results', 'status', 'updatedAt'] as const
  $columns = LearnLessonQuestionsQuizzSchema.$columns
  @column()
  declare answers: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare learnEnrollmentId: string
  @column()
  declare lessonId: string
  @column()
  declare questions: string
  @column()
  declare results: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LearnLessonViewSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'learnEnrollmentId', 'lessonId', 'updatedAt'] as const
  $columns = LearnLessonViewSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare learnEnrollmentId: string
  @column()
  declare lessonId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LearnQuestionSchema extends BaseModel {
  static $columns = ['attachment', 'courseId', 'createdAt', 'description', 'difficulty', 'id', 'losses', 'name', 'picture', 'response1', 'response2', 'response3', 'response4', 'response5', 'responseCorrect', 'updatedAt', 'wons'] as const
  $columns = LearnQuestionSchema.$columns
  @column()
  declare attachment: string | null
  @column()
  declare courseId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare difficulty: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare losses: number
  @column()
  declare name: string
  @column()
  declare picture: string | null
  @column()
  declare response1: string
  @column()
  declare response2: string
  @column()
  declare response3: string | null
  @column()
  declare response4: string | null
  @column()
  declare response5: string | null
  @column()
  declare responseCorrect: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare wons: number
}

export class SiteSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'expiresAt', 'id', 'logo', 'name', 'updatedAt', 'url'] as const
  $columns = SiteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare logo: string | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
}

export class SocialCommentSchema extends BaseModel {
  static $columns = ['active', 'commentableId', 'commentableType', 'content', 'createdAt', 'id', 'isEdited', 'parentId', 'siteId', 'updatedAt', 'userId'] as const
  $columns = SocialCommentSchema.$columns
  @column()
  declare active: boolean | null
  @column()
  declare commentableId: string
  @column()
  declare commentableType: string
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isEdited: boolean | null
  @column()
  declare parentId: string | null
  @column()
  declare siteId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class SocialReplySchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'id', 'topicId', 'updatedAt', 'userId'] as const
  $columns = SocialReplySchema.$columns
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare topicId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class SocialTopicSchema extends BaseModel {
  static $columns = ['active', 'content', 'createdAt', 'group', 'id', 'name', 'siteId', 'slug', 'updatedAt', 'userId'] as const
  $columns = SocialTopicSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare group: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare siteId: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class StoreAddressSchema extends BaseModel {
  static $columns = ['addressLine1', 'addressLine2', 'cityId', 'comments', 'createdAt', 'id', 'phone', 'postalCode', 'siteId', 'updatedAt', 'userId'] as const
  $columns = StoreAddressSchema.$columns
  @column()
  declare addressLine1: string
  @column()
  declare addressLine2: string | null
  @column()
  declare cityId: number | null
  @column()
  declare comments: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare phone: string | null
  @column()
  declare postalCode: string | null
  @column()
  declare siteId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class StoreCitySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'stateId', 'updatedAt'] as const
  $columns = StoreCitySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare stateId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StoreCouponSchema extends BaseModel {
  static $columns = ['active', 'code', 'createdAt', 'discount', 'discountType', 'expirationDate', 'id', 'minimumOrderValue', 'siteId', 'updatedAt'] as const
  $columns = StoreCouponSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare discount: string
  @column()
  declare discountType: string
  @column.dateTime()
  declare expirationDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare minimumOrderValue: string | null
  @column()
  declare siteId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StoreOrderSchema extends BaseModel {
  static $columns = ['billingAddress', 'createdAt', 'id', 'shippingAddress', 'siteId', 'status', 'total', 'updatedAt', 'userId'] as const
  $columns = StoreOrderSchema.$columns
  @column()
  declare billingAddress: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare shippingAddress: string | null
  @column()
  declare siteId: string
  @column()
  declare status: string
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class StoreOrderItemSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'orderId', 'price', 'productId', 'quantity', 'updatedAt'] as const
  $columns = StoreOrderItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare orderId: string
  @column()
  declare price: string
  @column()
  declare productId: string | null
  @column()
  declare quantity: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StorePaymentSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'currency', 'id', 'orderId', 'paymentMethod', 'paymentStatus', 'transactionId', 'updatedAt'] as const
  $columns = StorePaymentSchema.$columns
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currency: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare orderId: string
  @column()
  declare paymentMethod: string
  @column()
  declare paymentStatus: string
  @column()
  declare transactionId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StoreProductSchema extends BaseModel {
  static $columns = ['active', 'content', 'createdAt', 'description', 'id', 'name', 'picture', 'price', 'siteId', 'sizeD', 'sizeH', 'sizeW', 'slug', 'stock', 'tags', 'updatedAt', 'weight'] as const
  $columns = StoreProductSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare picture: string | null
  @column()
  declare price: string
  @column()
  declare siteId: string
  @column()
  declare sizeD: string | null
  @column()
  declare sizeH: string | null
  @column()
  declare sizeW: string | null
  @column()
  declare slug: string
  @column()
  declare stock: number
  @column()
  declare tags: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare weight: string | null
}

export class StoreProductAttributeSchema extends BaseModel {
  static $columns = ['id', 'name', 'productId', 'value'] as const
  $columns = StoreProductAttributeSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare productId: string
  @column()
  declare value: string
}

export class StoreShippingRuleSchema extends BaseModel {
  static $columns = ['active', 'cityId', 'createdAt', 'id', 'name', 'price', 'pricePerCm3', 'pricePerKg', 'siteId', 'stateId', 'updatedAt'] as const
  $columns = StoreShippingRuleSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare cityId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare price: string
  @column()
  declare pricePerCm3: string | null
  @column()
  declare pricePerKg: string | null
  @column()
  declare siteId: string
  @column()
  declare stateId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StoreStateSchema extends BaseModel {
  static $columns = ['code', 'country', 'createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = StoreStateSchema.$columns
  @column()
  declare code: string
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['avatar', 'createdAt', 'email', 'emailVerifiedAt', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatar: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
