/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ContentAttachmentSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'mime', 'name', 'path', 'siteId', 'size', 'userId'] as const
  $columns = ContentAttachmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mime: string
  @column()
  declare name: string
  @column()
  declare path: string
  @column()
  declare siteId: string
  @column()
  declare size: number
  @column()
  declare userId: string
}

export class ContentAttributeSchema extends BaseModel {
  static $columns = ['contentPostId', 'id', 'name', 'type', 'value'] as const
  $columns = ContentAttributeSchema.$columns
  @column()
  declare contentPostId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare type: string
  @column()
  declare value: string
}

export class ContentPostSchema extends BaseModel {
  static $columns = ['active', 'content', 'createdAt', 'description', 'format', 'id', 'name', 'picture', 'siteId', 'slug', 'tags', 'updatedAt', 'userId'] as const
  $columns = ContentPostSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare format: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare picture: string | null
  @column()
  declare siteId: string
  @column()
  declare slug: string
  @column()
  declare tags: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class EnrollmentSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'role', 'siteId', 'updatedAt', 'userId'] as const
  $columns = EnrollmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare role: string
  @column()
  declare siteId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class SiteSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'expiresAt', 'id', 'logo', 'name', 'updatedAt', 'url'] as const
  $columns = SiteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare logo: string | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
}

export class SocialCommentSchema extends BaseModel {
  static $columns = ['active', 'commentableId', 'commentableType', 'content', 'createdAt', 'id', 'isEdited', 'parentId', 'siteId', 'updatedAt', 'userId'] as const
  $columns = SocialCommentSchema.$columns
  @column()
  declare active: boolean | null
  @column()
  declare commentableId: string
  @column()
  declare commentableType: string
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isEdited: boolean | null
  @column()
  declare parentId: string | null
  @column()
  declare siteId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class SocialReplySchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'id', 'topicId', 'updatedAt', 'userId'] as const
  $columns = SocialReplySchema.$columns
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare topicId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class SocialTopicSchema extends BaseModel {
  static $columns = ['active', 'content', 'createdAt', 'group', 'id', 'name', 'siteId', 'slug', 'updatedAt', 'userId'] as const
  $columns = SocialTopicSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare group: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare siteId: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['avatar', 'createdAt', 'email', 'emailVerifiedAt', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatar: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
